config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :games do
      resources :questions, module: :games, only: [:new, :create]
    end 
  end
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "sessions#new"

  resources :games
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :game_users
  has_many :users, through: :game_users
  has_many :questions
end

app/models/game_user.rb
class GameUser < ApplicationRecord
  belongs_to :user
  belongs_to :game
  has_many :guesses
end

app/models/guess.rb
class Guess < ApplicationRecord
  belongs_to :game_user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :game
  has_many :guesses
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  has_many :game_users
  has_many :games, through: :game_users

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'
end

app/controllers/admin/games/questions_controller.rb
class Admin::Games::QuestionsController < Admin::BaseController
  before_action :set_game, only: %i[ new create]

  def new
    @question = Question.new
  end

  def create
  end

  private
    def set_game
      @game = Game.find(params.expect(:game_id))
    end

    def question_params
      params.expect(question: [ :title, :answer ])
    end
end

app/controllers/admin/games_controller.rb
class Admin::GamesController < Admin::BaseController
  before_action :set_game, only: %i[ show edit update destroy ]

  # GET /admin/games or /admin/games.json
  def index
    @games = Game.all
  end

  # GET /admin/games/1 or /admin/games/1.json
  def show
  end

  # GET /admin/games/new
  def new
    @game = Game.new
  end

  # GET /admin/games/1/edit
  def edit
  end

  # POST /admin/games or /admin/games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to [:admin, @game], notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/games/1 or /admin/games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to [:admin, @game], notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/games/1 or /admin/games/1.json
  def destroy
    @game.destroy!

    respond_to do |format|
      format.html { redirect_to admin_games_path, status: :see_other, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.expect(game: [ :title ])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      Current.session.present?
    end

    def require_authentication
      resume_session || request_authentication
    end


    def resume_session
      Current.session = find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id])
    end


    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_url
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end


    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_url, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_url, notice: "Password has been reset."
    else
      redirect_to edit_password_url(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_url, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_url, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_url
  end
end

app/helpers/admin/games_helper.rb
module Admin::GamesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/games/_form.html.erb
<%= form_with(model: [:admin, game], class: "contents") do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>
      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/admin/games/_game.html.erb
<%= link_to [:admin, game], id: dom_id(game), class: 'grid grid-cols-3 gap-px bg-slate-100 group hover:bg-blue-500 hover:text-white' do %>
  <div class='col-span-2 px-4 py-2 bg-white group-hover:bg-blue-500'><%= game.title %></div>
  <div class='px-4 py-2 bg-white group-hover:bg-blue-500'><%= pluralize(game.questions.count, 'question') %></div>
<% end %>

app/views/admin/games/edit.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to 'Games', admin_games_path %> </li>
  <li><%= link_to @game.title, admin_game_path(@game) %></li>
  <li>Edit</li>
<% end %>

<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing game</h1>

  <%= render "form", game: @game %>

  <%= link_to "Show this game", [:admin, @game], class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to games", admin_games_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/games/index.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to 'Games', admin_games_path %> </li>
<% end %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Games" %>

  <div class="flex justify-between items-center mb-4">
    <h1 class="font-bold text-4xl">Games</h1>
    <%= link_to "New game", new_admin_game_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="games" class="min-w-full rounded-lg shadow overflow-hidden ring-black/10 ring-1">
    <div class='grid grid-cols-3 text-sm gap-px bg-slate-100 font-semibold'>
      <div class='col-span-2 px-4 py-2'>Title</div>
      <div class='px-4 py-2'>Questions</div>
    </div>
    <% @games.each do |game| %>
      <%= link_to [:admin, game] do %>
        <%= render game %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/admin/games/new.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to 'Games', admin_games_path %> </li>
  <li>New</li>
<% end %>

<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New game</h1>

  <%= render "form", game: @game %>
  <%= link_to "Back to games", admin_games_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/games/questions/_form.html.erb
<%= form_with(model: [:admin, @game, question], class: "contents") do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>
      <ul>
        <% question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title, 'Question' %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :answer, 'Correct answer' %>
    <%= form.text_field :answer, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/admin/games/questions/new.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to 'Games', admin_games_path %> </li>
  <li><%= link_to @game.title, admin_game_path(@game) %></li>
  <li>New question</li>
<% end %>

<h1 class="font-bold text-4xl">New question</h1>
<%= render "form", question: @question %>

app/views/admin/games/show.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to 'Games', admin_games_path %> </li>
  <li><%= @game.title %></li>
<% end %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl mb-4"><%= @game.title %></h1>

  <p>
  <strong class="block font-medium mb-1">Questions:</strong>
  <% if @game.questions.empty? %>
    <em>No questions added yet</em>
  <% else %>
    <ol class='rounded shadow overflow-hidden bg-slate-100 grid grid-cols-1 gap-px ring-black/10 ring-1'>
      <%- @game.questions.each do | question | %>
        <li class='px-4 py-2 bg-white'><%= question.title %></li>
      <% end %>
        <li class='px-4 py-2 bg-white'><%= link_to '+ New question', new_admin_game_question_path(@game) %></li>
    </ol>
  <% end %>
  </p>

  <%= link_to "Edit this game", edit_admin_game_path(@game), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to games", admin_games_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this game", [:admin, @game], method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Guess That Bridge" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/views/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class='min-h-screen bg-slate-100'>
      <nav class='p-2 border-b border-slate-200 flex justify-between items-center'>
        <ol class='admin-breadcrumbs flex justify-start items-center [&_li+li:before]:content-["/"] [&_li+li:before]:opacity-30 [&_li+li:before] text-sm font-medium'>
          <li><%= link_to 'Guess that Bridge', '/admin/games' %></li>
          <%= yield :breadcrumbs %>
        </ol>
        <%= button_to "Sign out", session_path, method: :delete, class: "px-4 py-2 text-sm rounded font-medium hover:bg-gray-50" %>
      </nav>
      <div class='p-2'>
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Guess That Bridge" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/views/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>